In [1]:
import numpy as np


In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#random distribution of data 

In [12]:
np.random.rand(5,2)

array([[0.4444779 , 0.81249644],
       [0.13596608, 0.72265066],
       [0.31836074, 0.18207332],
       [0.49717756, 0.96877187],
       [0.99021132, 0.51741212]])

In [13]:
np.random.randn(10)

array([ 1.50943724,  0.62107392, -0.49705304, -0.84051264, -1.31874428,
       -0.16867936, -0.18708806,  1.07116438, -0.66614728,  2.04114606])

In [14]:
np.random.randint(0,101,10)

array([78, 24, 41, 11, 50, 69,  1, 18, 21, 87])

In [15]:
# seed is to get particular arbitary number 

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
# to get max and min value 

In [18]:
rearr = np.random.randint(0,101,10)

In [19]:
rearr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [20]:
rearr.max()

99

In [21]:
rearr.min()

2

In [22]:
rearr.argmax()

5

In [23]:
rearr.argmin()

7

In [24]:
# indexing and slicing 

In [27]:
arr = np.arange(0,101,10)

In [28]:
arr[0]

0

In [29]:
arr[1]

10

In [30]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
arr[1:5]

array([10, 20, 30, 40])

In [32]:
arr[:5]

array([ 0, 10, 20, 30, 40])

In [33]:
arr[5:]

array([ 50,  60,  70,  80,  90, 100])

In [34]:
arr[0:5] = 100

In [35]:
arr

array([100, 100, 100, 100, 100,  50,  60,  70,  80,  90, 100])

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# copying of one array values to another , without effecting original array 

In [39]:
arr_copy = arr.copy()

In [40]:
arr_copy[:5] = 99

In [41]:
arr_copy


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr_2d = np.array([[5,10,15],[20,35,30],[35,40,45]])

In [44]:
arr_2d


array([[ 5, 10, 15],
       [20, 35, 30],
       [35, 40, 45]])

In [45]:
arr_2d.shape

(3, 3)

In [46]:
arr_2d[0,2]

15

In [47]:
arr_2d[:2,1:]

array([[10, 15],
       [35, 30]])

In [48]:
# conditional selection 

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr>4

In [53]:
arr[boo_arr]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
#### Numpy Operations 

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr +5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [61]:
np.log(arr)

/var/folders/f7/m5k2nrk12tn1btvsv3dj0_nr0000gn/T/ipykernel_353/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [62]:
arr.max()

10

In [63]:
arr.min()

0

In [64]:
arr.std()

3.1622776601683795

In [65]:
arr.var()

10.0

In [67]:
arr2d = np.arange(0,25).reshape(5,5)

In [68]:
arr2d.sum()

300

In [69]:
# column sum 

In [70]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [71]:
#row sum

In [72]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [74]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])